name: cdk-github-actions-deploy
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Setup dependencies
        working-directory: aws
        run: npm ci
      - name: Setup lambda
        run: bash ./lamba-dependency.sh
      - name: CDK Deploy
        working-directory: aws
        run: npm run cdk deploy
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CHATGPT_APIKEY: ${{ secrets.CHATGPT_APIKEY }}
          DREAM_STUDIO_APIKEY: ${{ secrets.DREAM_STUDIO_APIKEY }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
